### ISSUE TITLE
coroutine 'build_graph' was never awaited [web response is stuck]

### ISSUE THREAD

**Issue by cchitwan** [google/adk-python#1233]
** Please make sure you read the contribution guide and file the issues in the right place. **
[Contribution guide.](https://google.github.io/adk-docs/contributing-guide/)

**Describe the bug**
When a question is about doing analysis on data and returing a table in the response. Web is showing for a long time fetching response trail. But it is not able to show table. When it is asked again what happened, it says the table is already give in the previous response.

Below is the info recieved from the log.

python3.12/site-packages/google/adk/cli/agent_graph.py:270: RuntimeWarning: coroutine 'build_graph' was never awaited
  build_graph(graph, sub_agent, highlight_pairs, agent)

**To Reproduce**
1. Install '...'
2. Run '....'
3. Open '....'

**Expected behavior**
Data in table should be loaded on web as response with summary.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Linux
 - Python version(python -V): 3.12
 - ADK version(pip show google-adk): 1.2.1

**Additional context**

**Comment by selcukgun** [comment]
this issue must have been fixed with https://github.com/google/adk-python/commit/3b1f2ae9bfdb632b52e6460fc5b7c9e04748bd50. 

please sync to head on main or try with the next release. feel free to reopen if yo ustill encounter the issue.

**Comment by chanchalchitwan** [comment]
@selcukgun Thanks for the confirmation. It looks like it is still not published to pypi. Any idea, when will it be published?
