### ISSUE TITLE
Bug: _function_declaration_to_tool_param dereferences parameters.required without None-check

### ISSUE THREAD

**Issue by rusherman** [google/adk-python#2774]
_in google/adk/models/lite_llm.py_, function _function_declaration_to_tool_param_ accesses function_declaration.parameters.required without checking whether function_declaration.parameters is None, causing an AttributeError when parameters is absent.

Affected code
- File: google/adk/models/lite_llm.py
- Function: _function_declaration_to_tool_param
- Problematic line: function_declaration.parameters.required

Repro steps
1) Create a FunctionDeclaration with parameters unset/None, e.g. types.FunctionDeclaration(name="foo").
2) Trigger tool conversion (e.g., via LlmRequest.config.tools[0].function_declarations).
3) Observe crash.

Actual behavior
AttributeError: 'NoneType' object has no attribute 'required'

Expected behavior
If parameters is None, skip adding required and do not raise.

Proposed fix
Replace:
if function_declaration.parameters.required:
    tool_params["function"]["parameters"]["required"] = function_declaration.parameters.required
With a None-check:
if function_declaration.parameters and function_declaration.parameters.required:
    tool_params["function"]["parameters"]["required"] = function_declaration.parameters.required

Notes
- The properties branch already guards for None; required should follow the same pattern.
- Optionally only set required when it’s a non-empty list to avoid emitting required: [].

Environment
- OS: macOS
- Python: 3.12
- Package: adk-python (exact version to be filled in)

**Comment by rusherman** [comment]
[fixed](https://github.com/google/adk-python/pull/2773)

**Comment by manessaraj** [comment]
This issue is still present why @rusherman bug ticket is closed?
