### ISSUE TITLE
llm_agent.py should not be saving though text parts to output_key

### ISSUE THREAD

**Issue by halfpasttense** [google/adk-python#976]
As the title says, thought parts should not be joined to the response text and saved to the output_key. Especially since there's no way to separate these again or to even know that part of it is thought text.

```python
  def __maybe_save_output_to_state(self, event: Event):
    """Saves the model output to state if needed."""
    if (
        self.output_key
        and event.is_final_response()
        and event.content
        and event.content.parts
    ):
      result = ''.join(
          [part.text if part.text and not part.thought else '' for part in event.content.parts] # modified to not include thought parts
      )
      if self.output_schema:
        result = self.output_schema.model_validate_json(result).model_dump(
            exclude_none=True
        )
      event.actions.state_delta[self.output_key] = result
```

**Comment by jwiejulie** [comment]
Hi @halfpasttense,

We're currently doing some housekeeping on our issue tracker. Given the rapid pace of development and the number of updates since this was last active, there's a good chance this issue has been resolved in a newer version. To help us keep our backlog focused on current issues, we are closing this as stale.

If you're still facing this problem, could you please update to the very latest version of the library and confirm the issue still exists? If it does, please comment here, and we will be happy to reopen this issue and investigate further.

Thanks for your contribution and understanding!

**Comment by halfpasttense** [comment]
Yes this is still an issue in the latest version. The faulty code has not been fixed.

**Comment by Sunriseaiteam** [comment]
Same here

**Comment by Jacksunwei** [comment]
This has been fixed in https://github.com/google/adk-python/commit/bb148002f8220412ca4e431964cc1ef36bff5f77
